# Generated by Django 2.2.13 on 2020-08-03 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBasket',
            fields=[
                ('basket_id', models.UUIDField(default=uuid.UUID('34a50e9f-5c1f-4c89-b3b6-04b327dfcf92'), primary_key=True, serialize=False, unique=True)),
                ('books', models.ManyToManyField(to='books.Book')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
