# Generated by Django 2.2.13 on 2020-07-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookcaseCart',
        ),
    ]
