# Generated by Django 2.2.13 on 2020-08-06 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_userbasket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasket',
            name='basket_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
