# Generated by Django 2.2.13 on 2020-08-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200806_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='loaned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
