# Generated by Django 2.2.13 on 2020-07-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200727_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcasecart',
            name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='bookcasecart',
            name='return_date',
        ),
    ]
